config/routes.rb
Rails.application.routes.draw do

  get 'geek_of_the_week/home', to: 'static_pages#gotw_home'
  get 'geek_of_the_week/about', to: 'static_pages#gotw_about'
  get 'geek_of_the_week', to: 'challenges#latest_challenge'
  get 'geek_of_the_week/guesses', to: 'guesses#index'

  get 'req_of_the_week/home', to: 'static_pages#rotw_home'
  get 'req_of_the_week/about', to: 'static_pages#rotw_about'
  get 'req_of_the_week', to: 'reqs#latest_req'

  get 'about', to: 'static_pages#about'

  put 'guesses/update_guess_status', to: 'guesses#update_guess_status', as: 'update_guess_status'
  post 'challenges/create', to: 'challenges#create', as: 'create_challenge'

  resources :users, :except => [:index, :show, :edit, :destroy] do
    get :autocomplete_user_first_name, :on => :collection
    get :autocomplete_user_last_name, :on => :collection
  end

  resources :geek_of_the_week, :controller => 'challenges', :only => [:new, :create, :latest_challenge]
  resources :guesses, :only => [:create, :destroy]

  resources :req_of_the_week, :controller => 'reqs', :only => [:new, :create, :latest_req]

    root 'static_pages#home'

end

app/models/req.rb
class Req < ActiveRecord::Base

  validates :title, presence: true
  validates :department, presence: true

  def self.get_department_name(id)
    DEPARTMENT_CONSTANTS.find {|dc| dc[:id] == id}[:name]
  end

  def previous
    Req.where('reqs.id < ?', self.id).last
  end

  def next
    Req.where('reqs.id > ?', self.id).first
  end  


end

app/controllers/reqs_controller.rb
class ReqsController < ApplicationController
  http_basic_authenticate_with name: ROTW_USERNAME, password: ROTW_PASSWORD, only: [:new, :create]
  before_action :set_req, only: [:show, :edit, :update, :destroy]

  # GET /reqs
  # GET /reqs.json
  def index
    @reqs = Req.all
  end

  # GET /reqs/1
  # GET /reqs/1.json
  def show
  end

  # GET /reqs/new
  def new
    @req = Req.new
  end

  # GET /reqs/1/edit
  def edit
  end

  def latest_req
    get_latest_req
    render 'show'
  end

  # POST /reqs
  # POST /reqs.json
  def create
    @req = Req.new(req_params)

    respond_to do |format|
      if @req.save
        flash[:notice] = 'Req was successfully created.'
        flash[:send_notification_email] = params[:req][:send_notification_email] == "true"
        format.html { redirect_to req_of_the_week_path}
      else
        flash[:alert] = 'There was a problem. Please resubmit the Req of the Week.'
        format.html { redirect_to new_req_of_the_week_path }
      end
    end
  end

  # PATCH/PUT /reqs/1
  # PATCH/PUT /reqs/1.json
  def update
    respond_to do |format|
      if @req.update(req_params)
        format.html { redirect_to @req, notice: 'Req was successfully updated.' }
        format.json { render :show, status: :ok, location: @req }
      else
        format.html { render :edit }
        format.json { render json: @req.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reqs/1
  # DELETE /reqs/1.json
  def destroy
    @req.destroy
    respond_to do |format|
      format.html { redirect_to reqs_url, notice: 'Req was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def req_params
      params.require(:req).permit(:title, :department, :manager, :description)
    end

    def set_req
      @challenge = get_latest_req
    end
    def get_latest_req
      @req = Req.last
    end
end

app/helpers/reqs_helper.rb
module ReqsHelper

  def req_email_content(new_req)
    email_string = "Dear Sparks,\n\n"

    email_string += "Here is the current \"Req of the Week\" challenge:\n"
    email_string += "Position: " + new_req.title + "\n"
    email_string += "Department: " + Req.get_department_name(new_req.department) + "\n"
    email_string += "Manager: " + new_req.manager + "\n"

    email_string += "\nYou can access the full job description on the GuideSpark careers page: http://www.guidespark.com/about/careers." 
    email_string += " You can always view the latest Req of the Week by visiting http://" + request.host + url_for(req_of_the_week_path) + "." 
    email_string += " Again, the Req of the Week pays an additional 2k on top of the standard employee referral bonus of 2k. That’s 4k in your pocket!\n\n"
    email_string += "Thanks for your help!\n\n"

    email_string += "Ryan"

    return email_string

  end

  def req_generate_mail
    return mail_to "test@test.com", "Company email", subject: "Req of the Week - " + Req.last.title + " - " + Date.today.to_formatted_s(:rfc822), body: req_email_content(Req.last), id: "autoEmail"
  end


  def friend_email_content(new_req)

    email_string = "Hey!\n\nThere's a great job opening at GuideSpark that I think you'd be perfect for. It's for a "
    email_string += new_req.title + " in the "
    email_string += Req.get_department_name(new_req.department) + " department, reporting to "
    email_string += new_req.manager + ".\n\n"

    email_string += "You can check out more details on the company's careers page:\n\t\t http://www.guidespark.com/about/careers \n\n"

    email_string += "Let me know if you're interested.\n"

  end

  def generate_friend_mail
    return mail_to "", "<span class='fa fa-envelope-o fa-lg'></span>".html_safe, subject: "Job opening at GuideSpark: " + Req.last.title, body: friend_email_content(Req.last), class: 'btn btn-sm btn-primary'
  end

end

app/views/reqs/_form.html.erb
<div class="row">

  <%= form_for(:req, url: req_of_the_week_path) do |f| %>

      <div class="field col-md-12 form-group">
        <%= f.text_field :title, :class => "form-control", :placeholder => "Req title" %>
      </div>

      <div class="col-md-12">
        <div class="field form-group">
          <%= f.select :department, options_for_select(DEPARTMENT_CONSTANTS.map { |x| [x[:name], x[:id]] }, 0), {}, {'class' => 'btn btn-default dropdown-toggle form-control', 'data-toggle' => 'dropdown'} %>
        </div>
      </div>

      <div class="field col-md-12 form-group">
        <%= f.text_field :manager, :class => "form-control", :placeholder => "Manager" %>
      </div>
      <div class="field col-md-12 form-group">
        <%= f.text_area :description, :class => "form-control", :placeholder => "Description" %>
      </div>

      <%= f.hidden_field(:send_notification_email, value: 'true') %>
      <div class="col-md-12 form-group">
              <span>
                  <input id="email_checkbox" type="checkbox" name="gg-checkbox-mail"
                  data-size="large" data-on-text="<span class='fa fa-check fa-lg'></span>"
                  data-off-text="<span class='fa fa-close fa-lg'></span>" data-label-text="<span class='fa fa-envelope-o fa-lg' style='color: #999'></span>"
                  checked>
              </span>
      </div>

      <div class="col-md-12 actions">
            <span class="input-group-btn">
             <%= f.submit :class => 'btn btn-primary', data: { 'confirm' => 'This will add a new req of the week. Are you sure?', 'confirm-fade' => true, 'confirm-title' => 'Start a new Req'} %>
         </span>
      </div>
  <% end %>

</div>

app/views/reqs/edit.html.erb
<h1>Editing req</h1>

<%= render 'form' %>

<%= link_to 'Show', @req %> |
<%= link_to 'Back', reqs_path %>

app/views/reqs/index.html.erb
<h1>Listing reqs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Department</th>
      <th>Manager</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reqs.each do |req| %>
      <tr>
        <td><%= req.title %></td>
        <td><%= Req.get_department_name(req.department) %></td>
        <td><%= req.manager %></td>
        <td><%= req.description %></td>
        <td><%= link_to 'Show', req %></td>
        <td><%= link_to 'Edit', edit_req_path(req) %></td>
        <td><%= link_to 'Destroy', req, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Req', new_req_path %>

app/views/reqs/new.html.erb
<% provide(:title, " | New") %>
<h1 class="text-center">New Req of the week</h1>

<%= render 'form' %>

<div class="back_button"><%= link_to 'Back to current req', get_home_path, :class => "btn btn-default"%></div>

app/views/reqs/show.html.erb
<div id="my-tab-content" class="tab-content">
    <h1 class="text-center">The Req of the Week is...</h1>

    <blockquote>
      <h2><%= @req.title %></h2>
      <% if @req.department %>
          <p>
            <strong>Department: </strong>
            <%= Req.get_department_name(@req.department) %>
          </p>
      <% end %>
      <% if !@req.manager.empty? %>
          <p>
            <strong>Manager: </strong>
            <%= @req.manager %>
          </p>
      <% end %>
      <% if !@req.description.empty? %>
          <p>
            <strong>Description: </strong>
            <%= simple_format(@req.description) %>
          </p>
      <% end %>
      <footer><p>More information on all open positions can always be found on the <a href="http://www.guidespark.com/about/careers">GuideSpark Careers page</a>.</p></footer>
    </blockquote>
</div>

<div><h4>Share with a friend: <%= generate_friend_mail %></h4></div>

<%= req_generate_mail if flash[:send_notification_email] %>