config/routes.rb
Rails.application.routes.draw do

  get 'geek_of_the_week/home', to: 'static_pages#gotw_home'
  get 'geek_of_the_week/about', to: 'static_pages#gotw_about'
  get 'geek_of_the_week', to: 'challenges#latest_challenge'
  get 'geek_of_the_week/guesses', to: 'guesses#index'

  get 'req_of_the_week/home', to: 'static_pages#rotw_home'
  get 'req_of_the_week/about', to: 'static_pages#rotw_about'
  get 'req_of_the_week', to: 'reqs#latest_req'

  get 'about', to: 'static_pages#about'

  put 'guesses/update_guess_status', to: 'guesses#update_guess_status', as: 'update_guess_status'
  post 'challenges/create', to: 'challenges#create', as: 'create_challenge'

  resources :users, :except => [:index, :show, :edit, :destroy] do
    get :autocomplete_user_first_name, :on => :collection
    get :autocomplete_user_last_name, :on => :collection
  end

  resources :geek_of_the_week, :controller => 'challenges', :only => [:new, :create, :latest_challenge]
  resources :guesses, :only => [:create, :destroy]

  resources :req_of_the_week, :controller => 'reqs', :only => [:new, :create, :latest_req]

    root 'static_pages#home'

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  has_many :guesses
  validates :question, presence: true, :uniqueness => {:scope => :answer}
  validates :answer,   presence: true

  def previous
    Challenge.where('challenges.id < ?', self.id).last
  end

  def next
    Challenge.where('challenges.id > ?', self.id).first
  end  


end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  http_basic_authenticate_with name: GOTW_USERNAME, password: GOTW_PASSWORD, only: [:new, :create]
  before_action :set_challenge, only: [:show, :edit, :update, :destroy, :latest_challenge]
  before_action :set_user, only: [:edit, :update, :show, :latest_challenge]

  # GET /challenges
  # GET /challenges.json
  def index
    @challenges = Challenge.all
  end

  # GET /challenges/1
  # GET /challenges/1.json
  def show
  end

  # GET /challenges/new
  def new
  end

  # GET /challenges/1/edit
  def edit
  end

  def latest_challenge
    flash[:tab] = 'leaderboard_tab' if params[:historic_challenge]
    render 'show'
  end

  # POST /challenges
  # POST /challenges.json
  def create
    # set user from username
    @user = find_user_by_name params[:challenge][:first_name].capitalize, params[:challenge][:last_name].capitalize

    cookies.permanent[:guess_game_first_name] = @user.first_name
    cookies.permanent[:guess_game_last_name] = @user.last_name

    @challenge = @user.challenges.new(challenge_params)

    #find user by first and last name
    #@challenge.user = User.find_by(first_name: :user_first_name.capitalize, last_name: :user_last_name.capitalize)
    if Challenge.all.count>1
      @previous_challenge=Challenge.all[-2]   
    else
      @previous_challenge = nil
    end


    respond_to do |format|
      if @challenge.save
        flash[:notice] = 'Challenge was successfully created.'
        flash[:send_notification_email] = params[:challenge][:send_notification_email] == "true"
        format.html { redirect_to geek_of_the_week_path}
      else
        flash[:alert] = 'The question with the same answer was asked before!'
        format.html { redirect_to new_geek_of_the_week_path }
      end
    end
  end

  # PATCH/PUT /challenges/1
  # PATCH/PUT /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        flash[:notice] = 'Challenge was successfully updated.'
        format.html { redirect_to geek_of_the_week_path}
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.json
  def destroy
    @challenge.destroy
    respond_to do |format|
      flash[:notice] = 'Challenge was successfully destroyed.'
      format.html { redirect_to geek_of_the_week_path}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = get_latest_challenge
      if Challenge.all.count>1
        @guesses=Guess.all
        @correct_guesses = !@guesses.empty? ? @guesses.where(:status => STATUS_RIGHT) : nil
      end
    end

    def set_user
      @user = @challenge.user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def challenge_params
      params.require(:challenge).permit(:question, :hint, :answer)
    end

    def get_latest_challenge
      @challenge = Challenge.last
    end

end

app/helpers/challenges_helper.rb
module ChallengesHelper

  def challenge_winners(challenge)
    if challenge
      winners = challenge.guesses.where(:status => STATUS_RIGHT)
    else
      winners = nil
    end
  end


  def email_content(complete_challenge, new_challenge)
    email_string = "Dear Sparks,\n\n"

    if complete_challenge
      email_string += "Here are the results of the current \"Geek of the Week\" competition:\n\n"

      email_string += "Challenge: " + complete_challenge.question + "\n"
      if !new_challenge.hint.blank?
        email_string += "Hint: " + complete_challenge.hint + "\n"
      end
      email_string += "Answer: " + complete_challenge.answer + "\n"
      email_string += "Setter: " + complete_challenge.user.first_name + " " + complete_challenge.user.last_name + "\n"

      if challenge_winners(complete_challenge).count > 0
        email_string += "Winning " + "Geek".pluralize(challenge_winners(complete_challenge).count) + ": "
        email_string += challenge_winners(complete_challenge).map { |guess| guess.user.first_name + " " + guess.user.last_name }.join(", ") + "\n\n"
      else
        email_string += "There were no Geek of the Weeks this week!\n\n"
      end
    end
    email_string += "Here is the new \"Geek of the Week\" challenge:\n"
    email_string += "Challenge: " + new_challenge.question + "\n"
    if !new_challenge.hint.blank?
      email_string += "Hint: " + new_challenge.hint + "\n"
    end

    email_string += "\nYou can enter the latest challenge by visiting http://" + request.host + url_for(geek_of_the_week_path) + " - good luck!\n\n"

    email_string += new_challenge.user.first_name

    return email_string

  end

  def generate_mail
    return mail_to "test@test.com", "Company email", subject: "Geek of the Week - "+Date.today.to_formatted_s(:rfc822), body: email_content(Challenge.last.previous, Challenge.last), id: "autoEmail"
  end

  def list_of_creator(id_field, id_name)
    if @correct_guesses
      sorted_guesses = @correct_guesses.order("#{id_name} desc")
      outputs = []
      last_id = sorted_guesses.first[id_field]
      last_count = 0
      sorted_guesses.each do |guess|
        if guess[id_field] == last_id || guess == sorted_guesses.first
          last_count += 1
        else
          outputs << {id: last_id, count: last_count}
          last_id = guess[id_field]
          last_count = 1
        end
      end
      outputs << {id: last_id, count: last_count}
      return outputs
    else
      return nil
    end
  end

  def sorted_list_of_creator(list)
    if list
      return list.sort_by { |item| item[:count] }.reverse #Needs to be descending so reverse!
    else
      return nil
    end
  end

  def list_of_geeks
    list_of_creator(:user_id, "user_id")
  end

  def sorted_list_of_geeks
    return sorted_list_of_creator(list_of_geeks)
  end


  def list_of_depts
    list_of_creator(:department, "department")
  end

  def sorted_list_of_depts
    return sorted_list_of_creator(list_of_depts)
  end

  def list_of_geeks_and_depts
    g_d_list = []
    geek_list = self.list_of_geeks

    geek_list.each do |g|
      tmp_hash = {}
      tmp_hash[:id] = g[:id]
      tmp_hash[:dept] = []
      g_d_list << tmp_hash
    end

    correct_g = !Guess.all.empty? ? Guess.all.where(:status => STATUS_RIGHT) : nil

    correct_g.each do |cg|
      tmp_hash = g_d_list.detect { |g| g[:id] == cg[:user_id] }
      dept_name = cg.department
      tmp_hash[:dept].push(dept_name) unless tmp_hash[:dept].include?(dept_name)
    end

    return g_d_list
  end

  def geek_depts(geek)
    if !@geeks_depts_list
      @geek_dept_list = list_of_geeks_and_depts
    end

    tmp_hash = @geek_dept_list.detect { |g| g[:id] == geek[:id] }

    return tmp_hash[:dept].map { |d| Guess.get_department_name(d) }

  end

  def dept_pie_chart
    dept_results = sorted_list_of_depts
    dept_list = []
    dept_results.each do |dept|
      dept_list << [Guess.get_department_name(dept[:id]),dept[:count]]
    end

    pie_chart = Highcharts.new do |chart|
      chart.chart(renderTo: 'piechart', type: 'pie')
      chart.title('Department Leaderboard')
      chart.plotOptions(allowPointSelect: true, cursor: 'pointer')
      chart.series([{type: 'pie', name: 'Geeks', data: dept_list }])
      chart.credits(enabled: false)
    end

    return pie_chart
  end


end

app/views/challenges/_answer.html.erb
<%= form_for(:guess, url: guesses_path) do |f| %>


    <%= render partial: 'layouts/username', locals: {:form => f, :show_department => true}%>

    <div class="input-group col-md-12">
      <div class="field form-group input-group">
        <span class="input-group-addon">Guess</span>
        <%= f.text_field :answer, :class => "form-control", :placeholder => "Your guess?" %>
        <span class="input-group-btn">
          <%= f.submit "Submit", :class => 'btn btn-primary' %>
        </span>
      </div>
    </div>

<% end %>

app/views/challenges/_form.html.erb
    <%= form_for(:challenge, url: create_challenge_path) do |f| %>

    <%= render partial: 'layouts/username', locals: {:form => f, :show_department => false} %>
    <div class="row">
        <div class="col-md-12 form-group">
            <%= f.text_field :question, :class => "form-control", :placeholder => "What is the question?" %>
        </div>

        <div class="col-md-12 form-group">
            <%= f.text_field :hint, :class => "form-control", :placeholder => "Any hints?" %>
        </div>

        <div class="col-md-12 form-group">
            <%= f.text_field :answer, :class => "form-control", :placeholder => "The answer is...?" %>
        </div>

        <%= f.hidden_field(:send_notification_email, value: 'true') %>
        <div class="col-md-12 form-group">
                <span>
                    <input id="email_checkbox" type="checkbox" name="gg-checkbox-mail"
                    data-size="large" data-on-text="<span class='fa fa-check fa-lg'></span>"
                    data-off-text="<span class='fa fa-close fa-lg'></span>" data-label-text="<span class='fa fa-envelope-o fa-lg' style='color: #999'></span>"
                    checked>
                </span>
        </div>
      <div class="col-md-12">
            <span class="input-group-btn">
             <%= f.submit "Start challenge!", :class => 'btn btn-primary', data: { 'confirm' => 'This will end the current challenge. Are you sure?', 'confirm-fade' => true, 'confirm-title' => 'Start a new challenge'} %>
         </span>
      </div>
    </div>

 <% end %>

app/views/challenges/edit.html.erb
<h1>Editing challenge</h1>

<%= render 'form' %>

<%= link_to 'Show', user_challenge_path(@user, @challenge) %> |
<%= link_to 'Back', user_challenges_path(@user) %>

app/views/challenges/index.html.erb
<h1>Listing challenges</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Hint</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @challenges.each do |challenge| %>
      <tr>
        <td><%= challenge.question %></td>
        <td><%= challenge.hint %></td>
        <td><%= challenge.answer %></td>
        <td><%= link_to 'Show', challenge_path(challenge) %></td>
        <td><%= link_to 'Edit', edit_challenge_path(challenge) %></td>
        <td><%= link_to 'Destroy', challenge_path(challenge), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Challenge', new_challenge_path %>

app/views/challenges/new.html.erb
<% provide(:title, " | New") %>
<h1 class="text-center">Set a new challenge</h1>

<%= render 'form' %>

<div class="back_button"><%= link_to 'Back to current challenge', get_home_path, :class => "btn btn-default"%></div>

app/views/challenges/show.html.erb
<% ['nav-pills nav-justified', 'nav-tabs'].each_with_index do |v,i|%>
    <ul id="tabs-<%= i %>" class="nav <%= v %>" data-tabs="tabs">
      <li class="col-xs-4<% unless flash[:tab] || flash[:tab] ==  'challenge_tab'%> active<% end %>">
        <a href="#challenge_tab" data-toggle="tab"><i class='fa fa-question'></i> Challenge</a>
      </li>
      <li class="col-xs-4<% if flash[:tab] ==  'guesses_tab'%> active<% end %>">
        <a href="#guesses_tab" data-toggle="tab"><i class='fa fa-lightbulb-o'></i> Guesses <span class="badge"><%= @challenge.guesses.size %></span></a>
      </li>
      <li class="col-xs-4<% if flash[:tab] ==  'leaderboard_tab'%> active<% end %>">
        <a href="#leaderboard_tab" data-toggle="tab"><i class='fa fa-trophy'></i> Leaderboard</a>
      </li>
    </ul>
<% end %>

<div id="my-tab-content" class="tab-content">
  <div class="tab-pane<% unless flash[:tab] || flash[:tab] ==  'challenge_tab'%> active<% end %>" id="challenge_tab">
    <h1 class="text-center challenge-lead-text">The question for this week is...</h1>

    <blockquote>
      <h3 class="challenge-question"><%= @challenge.question %></h3>
      <% if @challenge.hint %>
        <% if !@challenge.hint.empty? %>
          <p class="challenge-hint">
            <strong>Hint:</strong>
            <%= @challenge.hint %>
          </p>
        <% end %>
      <% end %>
      <footer class="challenge-setter"><%= "#{@user.first_name} #{@user.last_name}" %></footer>
    </blockquote>
    <%= render 'challenges/answer'%>
  </div>
  <div class="tab-pane<% if flash[:tab] ==  'guesses_tab'%> active<% end %>" id="guesses_tab">

    <h1 class="text-center">What others guessed...</h1>

    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2 class="panel-title">Current Guesses</h2>
      </div>
      <%= render partial: 'layouts/guesses', :locals => {:isAdmin => false, :guesses => @challenge.guesses}%>
    </div>
  </div>

  <div class="tab-pane<% if flash[:tab] ==  'leaderboard_tab'%> active<% end %>" id="leaderboard_tab">

    <%= render partial: 'leaderboard/leaderboard' %>
  </div>

</div>

<%= generate_mail if flash[:send_notification_email] %>