config/routes.rb
Rails.application.routes.draw do

  get 'geek_of_the_week/home', to: 'static_pages#gotw_home'
  get 'geek_of_the_week/about', to: 'static_pages#gotw_about'
  get 'geek_of_the_week', to: 'challenges#latest_challenge'
  get 'geek_of_the_week/guesses', to: 'guesses#index'

  get 'req_of_the_week/home', to: 'static_pages#rotw_home'
  get 'req_of_the_week/about', to: 'static_pages#rotw_about'
  get 'req_of_the_week', to: 'reqs#latest_req'

  get 'about', to: 'static_pages#about'

  put 'guesses/update_guess_status', to: 'guesses#update_guess_status', as: 'update_guess_status'
  post 'challenges/create', to: 'challenges#create', as: 'create_challenge'

  resources :users, :except => [:index, :show, :edit, :destroy] do
    get :autocomplete_user_first_name, :on => :collection
    get :autocomplete_user_last_name, :on => :collection
  end

  resources :geek_of_the_week, :controller => 'challenges', :only => [:new, :create, :latest_challenge]
  resources :guesses, :only => [:create, :destroy]

  resources :req_of_the_week, :controller => 'reqs', :only => [:new, :create, :latest_req]

    root 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="footer-left col-sm-6">
        <%= link_to image_tag("logo.png", :alt => "Guidespark Logo", height: '30'), "http://www.guidespark.com", target: '_blank' %> &copy;2014
      </div>
      <div class="footer-right col-sm-6">
        <%= link_to "Home", get_home_path %> | <%= link_to "About", get_about_path %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_guesses.html.erb
<div class="panel-body">
  <div class="span6 offset3">
    <table class="table table-striped ">
      <thead>
      <tr>
        <th>Guess</th>
        <th>Guesser</th>
        <% if isAdmin %>
        <th>Correct?</th>
        <th>Delete</th>
        <% end %>
      </tr>
      </thead>
      <tbody>
      <% guesses.each do |guess| %>
          <tr>
            <td> <%= guess.answer %> </td>
            <td> <%= guess.user.first_name %> <%= guess.user.last_name %> </td>
            <% if isAdmin %>
            <td>
              <input id="guess_eval_checkbox" type="checkbox" name="gg-checkbox"
                       data-size="large" data-on-text="<span class='fa fa-thumbs-up fa-lg'></span>"
                       data-off-text="<span class='fa fa-thumbs-down fa-lg'></span>"
                       <%= 'checked' unless guess.status == 0 %>
                       data-guess-id=<%= guess.id %>>
            </td>
            <td>
              <%= link_to '', guess_path(guess), :class => 'btn btn-danger fa fa-times', method: :delete, data: { 'confirm' => 'Are you sure?', 'confirm-fade' => true, 'confirm-title' => 'Delete guess'} %>
            </td>
            <% end %>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse" role="navigation">
  <div class="container">

    <% if @context == CONTEXT_UNDEFINED %>
      <p id="logo"><%= link_to image_tag("winsoftheweek.png", :alt => "Wins of the Week Logo", height: '32'), root_path %></p>
    <% elsif @context == CONTEXT_GEEK_OF_THE_WEEK %>
      <p id="logo"><%= link_to image_tag("geekoftheweek.png", :alt => "Geek of the Week Logo", height: '32'), geek_of_the_week_home_path %></p>
    <% elsif @context == CONTEXT_REQ_OF_THE_WEEK %>
      <p id="logo"><%= link_to image_tag("reqoftheweek.png", :alt => "Req of the Week Logo", height: '32'), req_of_the_week_home_path %></p>
    <% end %>


    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsed-content">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>


    <ul class="nav navbar-nav pull-left">
      <li class="dropdown" data-no-collapse="true">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="caret"></span> </a>
        <ul class="dropdown-menu centerDropdown" role="menu">
          <li><%= link_to image_tag("geekoftheweek.png", :alt => "Geek of the Week Logo", height: '32'), geek_of_the_week_home_path %></li>
          <li><%= link_to image_tag("reqoftheweek.png", :alt => "Req of the Week Logo", height: '32'), req_of_the_week_home_path %></li>
        </ul>
      </li>
    </ul>
    </div>

    <ul id="collapsed-content" class="nav navbar-nav pull-right collapse navbar-collapse">
      <li><%= link_to 'About', get_about_path %></li>
      <% if @context == CONTEXT_GEEK_OF_THE_WEEK %>
        <% if @challenge && @challenge.persisted? %>

          <li class="dropdown" data-no-collapse="true">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin<span class="caret"></span> </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Evaluate guesses', geek_of_the_week_guesses_path %></li>
              <li><%= link_to 'New Challenge', new_geek_of_the_week_path %></li>
            </ul>
          </li>
        <% end %>
      <% elsif @context == CONTEXT_REQ_OF_THE_WEEK %>
        <li class="dropdown" data-no-collapse="true">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin<span class="caret"></span> </a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'New Req of the Week', new_req_of_the_week_path %></li>
          </ul>
        </li>
      <% end %>

    </ul>

  </div>
</div>

app/views/layouts/_username.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="field form-group input-group">
      <span class="input-group-addon">First Name</span>
      <%= form.autocomplete_field :first_name, autocomplete_user_first_name_users_path, :value => cookies[:guess_game_first_name], :class => "form-control", :placeholder => "First Name" %>
    </div>

  </div>

  <div class="col-md-12">
    <div class="field form-group input-group">
      <span class="input-group-addon">Last Name</span>
      <%= form.autocomplete_field :last_name, autocomplete_user_last_name_users_path, :value => cookies[:guess_game_last_name], :class => "form-control", :placeholder => "Last Name" %>
    </div>
  </div>

  <% if show_department %>
      <div class="col-md-12">
        <div class="field form-group input-group">
          <span class="input-group-addon">Department</span>
          <%= form.select :department, options_for_select(DEPARTMENT_CONSTANTS.map { |x| [x[:name], x[:id]] }, cookies[:guess_game_department] || 0), {}, {'class' => 'btn btn-default dropdown-toggle form-control department-dropdown', 'data-toggle' => 'dropdown'} %>
        </div>
      </div>
  <% end %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    <% if @context == CONTEXT_UNDEFINED%>
        Wins of the Week
    <% elsif @context == CONTEXT_REQ_OF_THE_WEEK %>
        Req of the Week
    <% elsif @context == CONTEXT_GEEK_OF_THE_WEEK %>
        Geek of the Week
    <% end %>
    <%= yield(:title) %>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) && %w(notice alert).include?(name.to_s)%>
      <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> fade in">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
  <div class="row">

    <%= yield %>

  </div>


  <hr>

  <%= render 'layouts/footer' %>

</div>

</body>
</html>